# Generated by Django 4.0.1 on 2022-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('dob', models.DateField()),
                ('resident', models.TextField(max_length=150)),
                ('heart', models.BooleanField(default=False)),
                ('lungs', models.BooleanField(default=False)),
                ('kidneys', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False)),
                ('pancreas', models.BooleanField(default=False)),
                ('any_other_organ', models.BooleanField(default=False)),
                ('all_organs', models.BooleanField(default=False)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('corneas_or_eye_balls', models.BooleanField(default=False)),
                ('skin', models.BooleanField(default=False)),
                ('bones', models.BooleanField(default=False)),
                ('heart_valves', models.BooleanField(default=False)),
                ('blood_vessels', models.BooleanField(default=False)),
                ('any_other_tissue', models.BooleanField(default=False)),
                ('all_tissues', models.BooleanField(default=False)),
                ('sign', models.ImageField(upload_to='pledger')),
                ('address', models.TextField(max_length=150)),
                ('tel_no', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('witness1_name', models.CharField(max_length=100)),
                ('witness1_age', models.IntegerField(max_length=100)),
                ('witness1_dob', models.DateField()),
                ('witness1_resident', models.TextField(max_length=150)),
                ('witness1_tel_no', models.TextField(max_length=15)),
                ('witness1_email', models.EmailField(max_length=100)),
                ('witness1_relation', models.TextField(max_length=100)),
                ('witness2_name', models.CharField(max_length=100)),
                ('witness2_age', models.IntegerField(max_length=100)),
                ('witness2_dob', models.DateField()),
                ('witness2_resident', models.TextField(max_length=150)),
                ('witness2_tel_no', models.TextField(max_length=15)),
                ('witness2_email', models.EmailField(max_length=100)),
                ('witness2_relation', models.TextField(max_length=100)),
                ('witness_dated', models.DateField()),
                ('witness_place', models.CharField(max_length=100)),
                ('date_filled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
