# Generated by Django 4.0.1 on 2022-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness1_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness2_age',
            field=models.IntegerField(),
        ),
    ]
