# Generated by Django 4.0.1 on 2022-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_alter_pledge_age_alter_pledge_witness1_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='any_other_organ',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='any_other_tissue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
