# Generated by Django 4.0.1 on 2022-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_alter_pledge_any_other_organ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='all_organs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='all_tissues',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='blood_vessels',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='bones',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='corneas_or_eye_balls',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='heart',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='heart_valves',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='kidneys',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='liver',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='lungs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pancreas',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='resident',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='skin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='tel_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness1_relation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness1_resident',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness1_tel_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness2_relation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness2_resident',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='witness2_tel_no',
            field=models.CharField(max_length=15),
        ),
    ]
