# Generated by Django 4.0.1 on 2022-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_alter_pledge_all_organs_alter_pledge_all_tissues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='witness1_sign',
            field=models.ImageField(default=1, upload_to='pledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='witness2_sign',
            field=models.ImageField(default=1, upload_to='pledger'),
            preserve_default=False,
        ),
    ]
