# Generated by Django 4.0.1 on 2022-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_pledge_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
