# Generated by Django 4.0.1 on 2022-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0010_remove_pledge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
